version: "3"

# Uses the nginx container as a web proxy that sits in front of an apache web server.
services:
  proxy:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    ports:
      - "80:80" # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # ro means read-only
  web:
    image: httpd # this will use httpd:latest
