version: "2"

services:
  php-apache:
    image: php:7.2.12-apache
    ports:
      - "80:80"
    environment:
      SERVER_ENVIRONEMNT: development
      APPDB_USERNAME: phpdev
      APPDB_PASSWORD: phpdev
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7.24
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: phpdev
      MYSQL_PASSWORD: phpdev
      MYSQL_DATABASE: phpdev
    volumes:
      - mysql-dev:/var/lib/mysql

volumes: mysql-dev:
